app/urls.py
from django.urls import path 
from . import views

app_name = 'app'
urlpatterns = [

#----------------------------------------------login ----------------------------------------------------------------------------------------------------------
    path('',views.form_login, name= 'form_login'),
    path('iniciar_sesion/', views.iniciar_sesion, name="iniciar_sesion"),
    path('logout/', views.cerrar_sesion, name='cerrar_sesion'),
    path('emergencia/', views.emergencia , name = 'emergencia'),
#-------------------------------------------estudiante -------------------------------------------------------------------------------------------------------
    
    path('estudiante/', views.estudiante , name = 'estudiante'),
    path('estudiante_ver_lista_grupos/', views.estudiante_ver_lista_grupos , name = 'estudiante_ver_lista_grupos'),
    path('estudiante_ver_grupo/', views.estudiante_ver_grupo , name = 'estudiante_ver_grupo'),
    path('estudiante_ver_grupo/<int:id>/', views.materia_view, name='clases'),
#-------------------------------------------administrador -----------------------------------------------------------------------------------------------------
    path('administrador/', views.administrador , name = 'administrador'),
    path('docentes/listado', views.lista_docentes , name = 'lista_docentes'),
    path('grupos/crear/', views.form_crear_grupos , name = 'form_crear_grupos'),
    path('grupos/crear_post/', views.crear_grupo_post , name = 'crear_grupo'),
    path('grupos/editar/<int:id>/', views.form_editar_grupo_admi , name = 'form_editar_grupo_admi'),
    path('grupos/', views.ver_lista_grupos , name = 'ver_lista_grupos'),
    path('grupos/eliminar/<int:id>/', views.eliminar_grupos_admin , name = 'eliminar_grupos_admin'),
    path('grupos/eliminar_confirm/<int:id>/', views.eliminar_grupos_admin_post , name = 'eliminar_grupos_admin_post'),
    path('grupos/agregar_estudiante/<int:id>/', views.form_agregar_estudiante_grupo , name = 'form_agregar_estudiante_grupo'),
    path('docente/crear/', views.form_crear_profesor , name = 'form_crear_profesor'),
    path('docente/crear_post/', views.crear_profesor_post , name = 'crear_profesor'),
    path('grupos/ver_grupo/<int:id>/', views.ver_grupo_admin , name = 'ver_grupo_admin'),
    path('crear_estudiante/', views.form_crear_estudiante , name = 'form_crear_estudiante'),
    path('listado_estudiantes/', views.listado_estudiantes , name = 'listado_estudiantes'),
    path('editar_estudiantes/', views.editar_estudiantes , name = 'editar_estudiantes'),
    path('ver_profesor/', views.ver_profesor , name = 'ver_profesor'),
    path('lista_grupos/', views.lista_grupos, name = 'listadoGrupos'),
#-------------------------------------------- docente ----------------------------------------------------------------------------------------------------------
    path('docente/', views.docente , name = 'docente'),
    path('profe_crear_actividad/', views.profe_crear_actividad, name = 'profe_crear_actividad'),
    path('profe_crear_actividad/<int:id>/', views.crear_view, name='materia'),
    path('crear_view/', views.crear_actividad_post , name = 'crear_actividad'),
    path('profe_editar_actividad/', views.profe_editar_actividad, name = 'profe_editar_actividad'),
    path('profe_editar_actividad/<int:id>/', views.editar_view, name='editar'),
    path('profe_ver_actividad/', views.profe_ver_actividad , name = 'profe_ver_actividad'),
    path('profe_ver_actividad/<int:id>/', views.ver_actividad, name='ver'),
    path('profe_calificar_actividad/', views.profe_calificar_actividad , name = 'profe_calificar_actividad'),
    path('profe_calificar_actividad/<int:id>/', views.calificar_actividad , name = 'calificar'),
    path('calificar_actividad/', views.calificar_actividad_post , name = 'calificar_actividad'),
    path('profe_verlista_grupos/', views.profe_verlista_grupos , name = 'profe_verlista_grupos'),
    path('profe_ver_lista_grupo/', views.profe_ver_lista_grupo , name = 'profe_ver_lista_grupo'),
    path('profe_ver_lista_grupo/<int:id>/', views.View_lista_alumnos , name = 'lista'),
    path('profe_ver_estudiante/', views.profe_ver_estudiante , name = 'profe_ver_estudiante'),
    path('profe_ver_estudiante/<int:id>/', views.View_lista_alumnos2 , name = 'lista2'),
]

trabajo/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('app/',include('app.urls')),
    path('admin/', admin.site.urls),
]

app/templates/app/calificar_actividad.html
{% extends "app/base.html" %}
{% load static %}
{% block nombre %}     
<title>Area Docentes</title> 
{% endblock%}

<!-- -----------------------------------fin perfil------------------------------------------ -->
<!----------------------------------contenido---------------------------------------------------- -->
{% block contenido %}    
<div class = contenido>
    <h1 class="titulo">Sección de docente</h1>
    <h2 class ="subtitulo"> Bienvenidos</h2>
    <hr>
    <p> En esta seccion vamos a poder crear una actividad para la seccion de los docentes donde un profesor 
        va a poder crear una entrega para sus alumnos de una actividad como un taller, tarea, parcial o de un foro participativo.
        la cual va a ser calificada por el docente en otra seccion de la pagina.
    </p>
    <br>
    <hr>
    <h1>Calificar actividad </h1>
    
    <p>Permite a un profesor crear una actividad. Los datos para crear la actividad son:
        el id de la actividad y el id del grupo
    </p>
    <h4> Si el docente lo desea puede crear una de las actividades ya predeterminadas de las cuales 
        puede escoger taller,tarea, parcial, foro de opinion, quiz.
    </h4><hr>
    <h2>Busqueda realizada:</h2>
    <h1>Clase: {{ materias3.asignatura }}</h1>
    <h4>Codigo: {{ materias3.codigo }}</h4>
    <h2>Semestre: {{ materias3.semestre }}</h2>
    <table>
        <thead>
            <tr>
                <th>Descripcion</th>
                <th>id actividad</th>
            </tr>
        </thead>
        <tbody>
            {% for actividad in materias3.actividades.all %}
            <tr>
                <td>{{ actividad.descripcion }}</td>
                <td>{{ actividad.id }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
<br>
<p>Los estudiantes que pertenecen a este grupo son:</p><br>
    <h1>Lista de estudiantes</h1>
    <p>a continuacion vamos a ver una lista de estudiantes inscritos en el curso para este semestre.
    </p>
    <table>
        <thead>
            <tr>
                <th>Nombre estudiante</th>
                <th>Apellido estudiante</th>
                <th>Correo Institucional</th>
                <th>Nota</th>
            </tr>
        </thead>
        <tbody>
            {% for actividad in materias3.grupos.all %}
            <tr>
                <td>{{ actividad.estudiante.user.first_name }}</td>
                <td> {{ actividad.estudiante.user.last_name }}</td>
                <td> {{ actividad.estudiante.user.email }}</td>
                <td>{{ actividad.nota.valor }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>    
<br><br>    
<form action="{% url 'app:calificar_actividad' %}" method="POST">
    {% csrf_token %}
    <label>Escoger la actividad a calificar:</label>
    <br><br>
    <select name="actividad">
        {% for caso2 in actividades %}
        <option value="{{caso2.id}}">{{ caso2.descripcion }}</option>
        {% endfor %}
    </select>
<br><br>
    <label>Escoger estudiante a calificar:</label> 
    <select name="estudiante">
        {% for tarea in estudiante_grupo %}
        <option value="{{tarea.user.id}}">{{tarea.user.first_name}} {{tarea.user.last_name}}</option>
        {% endfor %}
    </select>
    <br><br><br>
</div>
{% endblock%}         

<!-- ---------------------------------- fin contenido--------------------------------------- -->
<!----------------------------------------menu---------------------------------------------- -->
{% block menu%}       
<div class="menu">
    <div id="sidebar">
        <h2>Menu</h2>
        <ul>  
            <li> <a href="{% url 'app:docente'  %}">Mas informacion</a></li>
            <li><a href="{% url 'app:profe_crear_actividad'  %}">Crear Actividad</a></li>
            <li><a href="{% url 'app:profe_editar_actividad'  %}">Editar Actividad</a></li>  
            <li><a href="{% url 'app:profe_ver_actividad'  %}">ver actividad</a></li>
            <li> <a href="{% url 'app:profe_calificar_actividad'  %}">Calificar Actividad</a></li>
            <li><a href="{% url 'app:profe_verlista_grupos'  %}">Ver lista de grupos</a></li>
            <li><a href="{% url 'app:profe_ver_lista_grupo'  %}">Ver grupo</a></li>       
            <li><a href="{% url 'app:profe_ver_estudiante'  %}">Ver estudiante</a></li>  
        </ul>
    </div>
</div> 
{% endblock%}     
<!-- -----------------------------------------------fin del menu---------------------------- -->

app/templates/app/formCrearEstudiante.html
{% extends "app/base.html" %}

{% block nombre %}     
<title>Crear Estudiante</title> 
{% endblock %}

{% block nombre_usuario%}
    <h2>ADMINISTRADOR</h2>
{% endblock %}

{% block contenido %} 

<div class="contenido">
    <form id="crearEstudiante" class="crearEstudiante">
        <h1>Crear estudiante</h1>

        <label for="apellido1">Apellidos: *</label>
        <input type="text" name="apellido1">
        
        <label for="nombre1">Nombres: *</label>
        <input type="text" name="nombres1">
        
        <label for="email1">Email: *</label>
        <input type="text" name="apellido1">

        <label for="codigo1">Código: *</label>
        <input type="text" name="codigo1">

        <label for="password1">contraseña: *</label>
        <input type="password" name="password1">
        <br>
        <button class="creaEstu">Crear</button>
        <a href="{% url 'app:administrador'%}" class="resetCreaEstu">Cerrar</a>
    </form>
</div>
{% endblock %} 


{% block menu %}
<div class="menu">
    <div class="btnGrupos">
        <h2>Grupos</h2>
        <div class="groups">
            <a href="{% url 'app:form_crear_grupos'%}"> Crear Grupos</a>
            <a href="{% url 'app:ver_lista_grupos'%}"> Listado de Grupos</a>
        </div>

    </div>

    <div class="btnProfesores">
        <div class="btnTeachers">
            <h2>Profesores</h2>
            <div class="teachers">
                <a href="{% url 'app:crear_profesor'%}"> Crear Docente</a>
                <a href="{% url 'app:lista_docentes'%}"> Listado Docentes</a>
            </div>
        </div>
    </div>
    
    <div class="btnEstudiantes">
        <h2>Estudiantes</h2>
        <div class="students">
            <a href="{% url 'app:form_crear_estudiante'%}"> Crear Estudiante</a>
            <a href="{% url 'app:listado_estudiantes'%}"> Listado de Estudiantes</a>

        </div>

    </div>
</div>
{% endblock %}  

app/templates/app/form_editar_view.html
{% extends "app/base.html" %}
{% block nombre %}     
<title>Area Docentes</title> 
{% endblock%}       
<!-- -----------------------------------fin perfil------------------------------------------ -->
<!----------------------------------contenido---------------------------------------------------- -->
{% block contenido %}        
<div class="contenido">
    <h1 class="titulo">Sección de docente</h1>
    <h2 class ="subtitulo"> Bienvenidos</h2>
    <hr>    
    <h1>Editar Actividad</h1>
    <p> En esta seccion vamos a poder Editar una actividad para la seccion de los docentes donde un profesor 
        va a poder crear una entrega para sus alumnos de una actividad como un taller, tarea, parcial o de un foro participativo.
        la cual va a ser calificada por el docente en otra seccion de la pagina.
    </p>
    <br>
    <h1>Clase: {{ materia1.asignatura }}</h1>
    <h4>Codigo: {{ materia1.codigo }}</h4>
    <h2>Semestre: {{ materia1.semestre }}</h2>
    <br><br>
    <form action="{% url 'app:crear_actividad' %}" method="POST">
        {% csrf_token %}
        <label>Editar Actividad :</label>
        <input type="text" name="descripcion">
        <button>Editar Actividad</button>
    </form>
<br><br>
    <table>
        <thead>
            <tr>
                <th>Id actividad</th>
                <th>Descripcion</th>
                <th>Grupo</th>
            </tr>
        </thead>
        <tbody>
            {% for actividad in materia1.actividades.all %}
            <tr>
                <td>{{ actividad.id }}</td>
                <td>{{ actividad.descripcion }}</td>
                <td>{{ actividad.grupo }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <br><br>
</div>
{% endblock%}            

<!-- ---------------------------------- fin contenido--------------------------------------- -->
<!----------------------------------------menu---------------------------------------------- -->
{% block menu%}       
<div class="menu">
    <div id="sidebar">
        <h2>Menu</h2>
        <ul>  
            <li> <a href="{% url 'app:docente'  %}">Mas informacion</a></li>
            <li><a href="{% url 'app:profe_crear_actividad'  %}">Crear Actividad</a></li>
            <li><a href="{% url 'app:profe_editar_actividad'  %}">Editar Actividad</a></li>  
            <li><a href="{% url 'app:profe_ver_actividad'  %}">ver actividad</a></li>
            <li> <a href="{% url 'app:profe_calificar_actividad'  %}">Calificar Actividad</a></li>
            <li><a href="{% url 'app:profe_verlista_grupos'  %}">Ver lista de grupos</a></li>
            <li><a href="{% url 'app:profe_ver_lista_grupo'  %}">Ver grupo</a></li>       
            <li><a href="{% url 'app:profe_ver_estudiante'  %}">Ver estudiante</a></li>  
        </ul>
    </div>
</div> 
{% endblock%}  
<!-- -----------------------------------------------fin del menu---------------------------- -->
      

app/templates/app/profe_crear_actividad.html
{% extends "app/base.html" %}
{% load static %}
{% block nombre %}     
<title>Area estudiante</title> 
{% endblock%}

<!-- -----------------------------------fin perfil------------------------------------------ -->
<!----------------------------------contenido---------------------------------------------------- -->
{% block contenido %}  
<div class="contenido">
    <h1 class="titulo">Sección de docente</h1>
    <h2 class ="subtitulo"> Bienvenidos</h2>
    <hr>
    <p> En esta seccion vamos a poder crear una actividad para la seccion de los docentes donde un profesor 
        va a poder crear una entrega para sus alumnos de una actividad como un taller, tarea, parcial o de un foro participativo.
        la cual va a ser calificada por el docente en otra seccion de la pagina.
    </p>
    <br>
    <hr>
    <h1>Crear actividad </h1>

    <p>Permite a un profesor crear una actividad. Los datos para crear la actividad son:
        el id de la actividad y el id del grupo.
    </p>
    <br>
    <table>
        <thead>
            <th>Semestre</th>
            <th> Asignatura </th>
            <th>Codigo</th>
            <th>Crear Actividad</th>
        </thead>
        {% for materia in materias %}
        <tbody>
            <td>
                {% if materia.semestre %}
                {{ materia.semestre }}
                {% endif %}
            </td>
            <td>
                {% if materia.asignatura %}
                {{ materia.asignatura }}
                {% endif %}
            </td>
            <td>
                {% if materia.codigo %}
                {{ materia.codigo }}
                {% endif %}
            </td>
            <td>
                <a href="{% url 'app:materia' materia.id %}"><i class="fas fa-pencil-alt"></i></a>
            </td>
        </tbody>
        {% endfor %}
    </table>
<br><br>
<a href="{% url 'app:docente'  %}">Volver</a> 
<br> <br>
</div>
{% endblock%}             
<!-- ---------------------------------- fin contenido--------------------------------------- -->
<!----------------------------------------menu---------------------------------------------- -->
{% block menu%}       
<div class="menu">
    <div id="sidebar">
        <h2>Menu</h2>
        <ul>  
            <li> <a href="{% url 'app:docente'  %}">Mas informacion</a></li>
            <li><a href="{% url 'app:profe_crear_actividad'  %}">Crear Actividad</a></li>
            <li><a href="{% url 'app:profe_editar_actividad'  %}">Editar Actividad</a></li>  
            <li><a href="{% url 'app:profe_ver_actividad'  %}">ver actividad</a></li>
            <li> <a href="{% url 'app:profe_calificar_actividad'  %}">Calificar Actividad</a></li>
            <li><a href="{% url 'app:profe_verlista_grupos'  %}">Ver lista de grupos</a></li>
            <li><a href="{% url 'app:profe_ver_lista_grupo'  %}">Ver grupo</a></li>       
            <li><a href="{% url 'app:profe_ver_estudiante'  %}">Ver estudiante</a></li>  
        </ul>
    </div>
</div> 
{% endblock%}  
<!-- -----------------------------------------------fin del menu---------------------------- -->

app/templates/app/profe_ver_estudiante.html
{% extends "app/base.html" %}
{% block nombre %}     
<title>Area docente</title> 
{% endblock%}
<!-- -----------------------------------fin perfil------------------------------------------ -->
<!----------------------------------contenido---------------------------------------------------- -->
{% block contenido %}  
<div class="contenido">
    <h1 class="titulo">Sección de Docente</h1>
    <h2 class ="subtitulo"> Bienvenidos</h2>
    <h1> Buscar Estudiante </h1> 
    <hr>
    <br>
    <p> al insertar el id del grupo y del estudiante le permite a un profesor ver la información de un grupo asignado al profesor. Los datos requeridos para ver la información del estudiante son:</p>
    <p>En la siguiente pagina vamos a poder visualisar la informacion de los 
        grupos del docente en la cual vamos a poder la informacion respectiva de los 
        alumnos inscritos en las clases.
    </p>
    <br>
    <table>
        <thead>
            <th>Semestre</th>
            <th>Codigo</th>
            <th>Asignatura </th>

            <th>Lista Estudiantes</th>
        </thead>
        {% for lista2 in materias %}
        <tbody>
            <td>
                {% if lista2.semestre %}
                {{ lista2.semestre }}
                {% endif %}
            </td>
            <td>
                {% if lista2.codigo %}
                {{ lista2.codigo }}
                {% endif %}
            </td>
            <td>
                {% if lista2.asignatura %}
                {{ lista2.asignatura }}
                {% endif %}
            </td>
            <td>
                <a href="{% url 'app:lista2' lista2.id %}"><i class="fas fa-address-book"></i></a>
            </td>
        </tbody>
        {% endfor %}
    </table>>
</div>
{% endblock%}       

<!-- ---------------------------------- fin contenido--------------------------------------- -->
<!----------------------------------------menu---------------------------------------------- -->
{% block menu%}       
<div class="menu">
    <div id="sidebar">
        <h2>Menu</h2>
        <ul>  
            <li> <a href="{% url 'app:docente'  %}">Mas informacion</a></li>
            <li><a href="{% url 'app:profe_crear_actividad'  %}">Crear Actividad</a></li>
            <li><a href="{% url 'app:profe_editar_actividad'  %}">Editar Actividad</a></li>  
            <li><a href="{% url 'app:profe_ver_actividad'  %}">ver actividad</a></li>
            <li> <a href="{% url 'app:profe_calificar_actividad'  %}">Calificar Actividad</a></li>
            <li><a href="{% url 'app:profe_verlista_grupos'  %}">Ver lista de grupos</a></li>
            <li><a href="{% url 'app:profe_ver_lista_grupo'  %}">Ver grupo</a></li>       
            <li><a href="{% url 'app:profe_ver_estudiante'  %}">Ver estudiante</a></li>  
        </ul>
    </div>
</div> 
{% endblock%}  
<!-- -----------------------------------------------fin del menu---------------------------- -->
       

app/templates/app/verListaDocentes.html
{% extends "app/base.html" %}

{% block nombre %}     
<title>Listado Docentes</title> 
{% endblock %}

{% block nombre_usuario%}
    <h2>ADMINISTRADOR</h2>
{% endblock %}

{% block contenido %} 
<div class="contenido">
    {% comment %}
        <!-- VER LISTA PROFESORES -->
    {% endcomment %}

    <div id="verListaProfesores" class="verListaProfesores">
        <h3>LISTA DE PROFESORES</h3> 
        <br>
        <table>
            <thead>
                <tr>
                    <th>APELLIDOS</th>
                    <th>NOMBRES</th>
                    <th> EMAIL</th>
                    <th></th>
                </tr>
            </thead>


            {% for docente in docentes %}
            <tr>
                <td>{{docente.last_name}}</td>
                <td>{{docente.first_name}}</td>
                <td>{{docente.email}} </td>
                <td><a href="#" title="Ver docente" class="icon"><i class="fas fa-eye"></i></a></td>
            </tr>
            {% endfor %}
        </table>
        <a href="{% url 'app:administrador'%}" class="resetVerLista">Cerrar</a>
    </div>

</div>
{% endblock %} 


{% block menu %}
<div class="menu">
    <div class="btnGrupos">
        <h2>Grupos</h2>
        <div class="groups">
            <a href="{% url 'app:form_crear_grupos'%}"> Crear Grupo</a>
            <a href="{% url 'app:ver_lista_grupos'%}"> Listado de Grupos</a>
        </div>

    </div>

    <div class="btnProfesores">
        <div class="btnTeachers">
            <h2>Profesores</h2>
            <div class="teachers">
                <a href="{% url 'app:form_crear_profesor'%}"> Crear Docente</a>
                <a href="{% url 'app:lista_docentes'%}"> Listado Docentes</a>
            </div>
        </div>
    </div>
    
    <div class="btnEstudiantes">
        <h2>Estudiantes</h2>
        <div class="students">
            <a href="{% url 'app:form_crear_estudiante'%}"> Crear Estudiante</a>
            <a href="{% url 'app:listado_estudiantes'%}"> Listado Estudiantes</a>
        </div>

    </div>
</div>
{% endblock %}  

app/templates/app/verListaGruposAdmi.html
{% extends "app/base.html" %}

{% block nombre %}     
<title>Listado Grupos</title> 
{% endblock %}

{% block nombre_usuario%}
    <h2>ADMINISTRADOR</h2>
{% endblock %}

{% block contenido %} 
<div class="contenido">

    {% comment %}
        VER LISTA GRUPOS
    {% endcomment %}

    <div id="verListaGrupos" class="verListaGrupos">
        <h3 class="h3">LISTADO DE GRUPOS</h3>
        <br>
        <table>
            <thead>
                <tr>
                    <th>Código de Grupo</th>
                    <th>Asignatura</th>
                    <th>Profesor</th>
                    <th>Cantidad Estudiantes</th>
                </tr>

                </thead>

            <tbody>
                {% for grupo in groups %}
                <tr>
                    <td>{{grupo.codigo}} </td>
                    <td>{{grupo.asignatura}}</td>
                    <td>{{grupo.profesor}} </td>
                    <td>filtro para contar cantidad de estudiantes de cada curso </td>
                    <td> <a href="{% url 'app:form_editar_grupo_admi' grupo.id %}" title="editar grupo" class="icon"><i class="fas fa-edit"></i></a> </td>
                    <td> <a href="{% url 'app:ver_grupo_admin' grupo.id %}" title="ver grupo" class="icon"><i class="fas fa-eye"></i></a> </td>
                    <td> <a href="{% url 'app:eliminar_grupos_admin' grupo.id %}" title="eliminar grupo" class="icon_red"><i class="fas fa-trash-alt"></i></a> </td>
                    <td> <a href="{% url 'app:form_agregar_estudiante_grupo' grupo.id %}" title="agregar estudiante" class="icon_green"><i class="fas fa-user-plus"></i></a> </td>
                </tr>
                {% endfor %}
            </tbody>

        </table>
        <div>
            <a href="{% url 'app:administrador'%}" class="btnVerListaGrupo">Cerrar</a>
        </div>
    </div>
</div>
{% endblock %} 


{% block menu %}
<div class="menu">
    <div class="btnGrupos">
        <h2>Grupos</h2>
        <div class="groups">
            <a href="{% url 'app:form_crear_grupos'%}"> Crear Grupo</a>
            <a href="{% url 'app:ver_lista_grupos'%}"> Listado de Grupos</a>
        </div>

    </div>

    <div class="btnProfesores">
        <div class="btnTeachers">
            <h2>Profesores</h2>
            <div class="teachers">
                <a href="{% url 'app:crear_profesor'%}"> Crear Docente</a>
                <a href="{% url 'app:lista_docentes'%}"> Listado Docentes</a>
            </div>
        </div>
    </div>
    
    <div class="btnEstudiantes">
        <h2>Estudiantes</h2>
        <div class="students">
            <a href="{% url 'app:form_crear_estudiante'%}"> Crear Estudiante</a>
            <a href="{% url 'app:listado_estudiantes'%}"> Listado Estudiantes</a>
        </div>

    </div>
</div>
{% endblock %}  

app/templates/app/ver_actividad.html
{% extends "app/base.html" %}
{% block nombre %}     
<title>Area Docentes</title> 
{% endblock%}
<!-- -----------------------------------fin perfil------------------------------------------ -->
<!----------------------------------contenido---------------------------------------------------- -->
{% block contenido %}     
<div class="contenido">
    <h1 class="titulo">Sección de docente</h1>
    <h2 class ="subtitulo"> Bienvenidos</h2>
<h2>Busqueda realizada:</h2>

    <h1> Grupos asignados </h1> 
    <p>los grupos a su cargo son los siguientes, por favor espere a que carguen si da click en la pestaña de ver sobre la tabla podra ver una 
        lista de los alumnos que pertenecen al curso, ademas de poder ver su nota actual sobre el total del curso.
    </p>
    <hr>
    <h1>Clase: {{ materia.asignatura }}</h1>
    <h4>Codigo: {{ materia.codigo }}</h4>
    <h2>Semestre: {{ materia.semestre }}</h2>
    {% if materia.grupos.count > 0 %}
    <h1>Lista de estudiantes</h1>
    <p>a continuacion vamos a ver una lista de estudiantes inscritos en el curso para este semestre.
    </p>
    <br><br>
    <table>
        <thead>
            <tr>
                <th>Nombre estudiante</th>
                <th>Apellido estudiante</th>
                <th>Correo Institucional</th>
                <th>Nota</th>
            </tr>
        </thead>
        <tbody>
            {% for actividad in materia.grupos.all %}
            <tr>
                <td>{{ actividad.estudiante.user.first_name }}</td>
                <td> {{ actividad.estudiante.user.last_name }}</td>
                <td> {{ actividad.estudiante.user.email }}</td>
                <td>{{ actividad.nota.valor }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endif %}
<br><br>
</div>
{% endblock%} 
<!-- ---------------------------------- fin contenido--------------------------------------- -->
<!----------------------------------------menu---------------------------------------------- -->
{% block menu%}       
<div class="menu">
    <div id="sidebar">
        <h2>Menu</h2>
        <ul>  
            <li> <a href="{% url 'app:docente'  %}">Mas informacion</a></li>
            <li><a href="{% url 'app:profe_crear_actividad'  %}">Crear Actividad</a></li>
            <li><a href="{% url 'app:profe_editar_actividad'  %}">Editar Actividad</a></li>  
            <li><a href="{% url 'app:profe_ver_actividad'  %}">ver actividad</a></li>
            <li> <a href="{% url 'app:profe_calificar_actividad'  %}">Calificar Actividad</a></li>
            <li><a href="{% url 'app:profe_verlista_grupos'  %}">Ver lista de grupos</a></li>
            <li><a href="{% url 'app:profe_ver_lista_grupo'  %}">Ver grupo</a></li>       
            <li><a href="{% url 'app:profe_ver_estudiante'  %}">Ver estudiante</a></li>  
        </ul>
    </div>
</div> 
{% endblock%}  

<!-- -----------------------------------------------fin del menu---------------------------- -->